--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: POWER_UNIT; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."POWER_UNIT" (
    id bigint NOT NULL,
    station_id bigint NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    date_of_next_service timestamp with time zone NOT NULL,
    count_sensor bigint NOT NULL
);


ALTER TABLE public."POWER_UNIT" OWNER TO postgres;

--
-- Name: POWER_UNIT_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."POWER_UNIT" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."POWER_UNIT_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ROLE; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ROLE" (
    id bigint NOT NULL,
    name text NOT NULL
);


ALTER TABLE public."ROLE" OWNER TO postgres;

--
-- Name: ROLE_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ROLE" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ROLE_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: STATION; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."STATION" (
    id bigint NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public."STATION" OWNER TO postgres;

--
-- Name: STATION_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."STATION" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."STATION_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: USER; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."USER" (
    id bigint NOT NULL,
    first_name text NOT NULL,
    second_name text NOT NULL,
    patronymic text NOT NULL,
    email text NOT NULL,
    "Password" text DEFAULT ''::text NOT NULL,
    "RoleId" bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public."USER" OWNER TO postgres;

--
-- Name: USER_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."USER" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."USER_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: POWER_UNIT; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."POWER_UNIT" (id, station_id, name, created_at, date_of_next_service, count_sensor) FROM stdin;
2	8	Синий	2025-03-10 18:08:07.879997+03	2025-03-10 18:08:00.436+03	0
3	8	Синий2	2025-03-10 18:08:11.494373+03	2025-03-10 18:08:00.436+03	0
4	8	Синий3	2025-03-10 18:08:13.411481+03	2025-03-10 18:08:00.436+03	0
5	8	Синий43	2025-03-10 18:08:15.922143+03	2025-03-10 18:08:00.436+03	0
6	6	Зеленый2	2025-03-10 18:08:22.20355+03	2025-03-10 18:08:00.436+03	0
7	6	Зеленый3	2025-03-10 18:08:24.13736+03	2025-03-10 18:08:00.436+03	0
1	6	уже не зеленый	-infinity	2025-03-10 17:15:58.25+03	3
\.


--
-- Data for Name: ROLE; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ROLE" (id, name) FROM stdin;
1	Admin
2	User
\.


--
-- Data for Name: STATION; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."STATION" (id, name, created_at) FROM stdin;
8	Ольховатка	2025-03-10 18:04:24.204185+03
6	Иваново	-infinity
9	string	2025-03-11 20:56:30.456655+03
10	string	2025-03-11 20:56:33.507016+03
\.


--
-- Data for Name: USER; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."USER" (id, first_name, second_name, patronymic, email, "Password", "RoleId") FROM stdin;
1	Ivan	Ivanov	Ivanovich	admin@mail.ru	8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918	1
2	Semen	Semenov	Semenovich	user@mail.ru	04F8996DA763B7A969B1028EE3007569EAF3A635486DDAB211D512C85B9DF8FB	2
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250306195729_InitialCreate	9.0.2
20250311174212_Second	9.0.2
\.


--
-- Name: POWER_UNIT_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."POWER_UNIT_id_seq"', 9, true);


--
-- Name: ROLE_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ROLE_id_seq"', 3, false);


--
-- Name: STATION_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."STATION_id_seq"', 10, true);


--
-- Name: USER_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."USER_id_seq"', 3, false);


--
-- Name: POWER_UNIT PK_POWER_UNIT; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."POWER_UNIT"
    ADD CONSTRAINT "PK_POWER_UNIT" PRIMARY KEY (id);


--
-- Name: ROLE PK_ROLE; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ROLE"
    ADD CONSTRAINT "PK_ROLE" PRIMARY KEY (id);


--
-- Name: STATION PK_STATION; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."STATION"
    ADD CONSTRAINT "PK_STATION" PRIMARY KEY (id);


--
-- Name: USER PK_USER; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."USER"
    ADD CONSTRAINT "PK_USER" PRIMARY KEY (id);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_POWER_UNIT_station_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_POWER_UNIT_station_id" ON public."POWER_UNIT" USING btree (station_id);


--
-- Name: IX_USER_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_USER_RoleId" ON public."USER" USING btree ("RoleId");


--
-- Name: POWER_UNIT FK_POWER_UNIT_STATION_station_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."POWER_UNIT"
    ADD CONSTRAINT "FK_POWER_UNIT_STATION_station_id" FOREIGN KEY (station_id) REFERENCES public."STATION"(id) ON DELETE CASCADE;


--
-- Name: USER FK_USER_ROLE_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."USER"
    ADD CONSTRAINT "FK_USER_ROLE_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."ROLE"(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

